In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import SelectKBest, f_regression
from scipy.stats import pearsonr
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv('googleplaystore_filtered_last.csv', thousands = ',')

In [7]:
df.head()

Category  Rating    Reviews  Size  Installs  Type  Content Rating  \
0  4.344262       4   5.075174  19.0     10000     0               3   
1  4.344262       4   6.875232  14.0    500000     0               3   
2  4.344262       5  11.379520   8.7   5000000     0               3   
3  4.344262       4  12.281389  25.0    100000     0               4   
4  4.344262       4   6.875232   2.8    100000     0               3   

   year_added  month_added  
0        2018            1  
1        2018            1  
2        2018            8  
3        2018            6  
4        2018            6

In [6]:
x = df.drop('Rating', axis=1)
y = df['Rating']
display(x)
display(y)

Category    Reviews   Size  Installs  Type  Content Rating  year_added  \
0     4.344262   5.075174  19.00     10000     0               3        2018   
1     4.344262   6.875232  14.00    500000     0               3        2018   
2     4.344262  11.379520   8.70   5000000     0               3        2018   
3     4.344262  12.281389  25.00    100000     0               4        2018   
4     4.344262   6.875232   2.80    100000     0               3        2018   
...        ...        ...    ...       ...   ...             ...         ...   
7953  4.213333   1.791759   0.84       100     1               3        2018   
7954  4.148026   1.098612  16.00         1     1               3        2017   
7955  4.204819   3.583519   2.40      1000     1               3        2018   
7956  4.148026   5.533389  11.00     10000     1               4        2015   
7957  4.089552   7.248504   9.50     10000     1               3        2018   

      month_added  
0               1  
1               1  
2               8  
3               6  
4               6  
...           ...  
7953            4  
7954            3  
7955            8  
7956            2  
7957            6  

[7958 rows x 8 columns]

0       4
1       4
2       5
3       4
4       4
       ..
7953    5
7954    5
7955    4
7956    4
7957    4
Name: Rating, Length: 7958, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [9]:
print(len(x_train), len(df))


6366 7958


In [12]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(x_train, y_train)

pred = lr.predict(x_test)
print(pred)

[4 4 4 ... 4 4 4]


c:\python39\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, pred)
print(cm)

score = accuracy_score(y_test, pred)
print(score)

[[   0    0    0    4    0]
 [   0    0    0   20    0]
 [   0    0    0  130    0]
 [   0    0    0 1106    0]
 [   0    0    0  332    0]]
0.6947236180904522


In [14]:
def predict(ml_model, x_train, y_train, x_test, y_test):
    model = ml_model.fit(x_train, y_train)
    pred = model.predict(x_test)
    print(f'예측값: {pred}')
    
    cm = confusion_matrix(y_test, pred)
    print(f'성능 평가 매트릭스: {cm}')

    score = accuracy_score(y_test, pred)
    print(f'평가 점수: {score}')
    

In [17]:
from sklearn.ensemble import RandomForestClassifier

predict(RandomForestClassifier(), x_train, y_train, x_test, y_test)

예측값: [4 4 4 ... 4 4 4]
성능 평가 매트릭스: [[   0    0    1    1    2]
 [   1    0    2   15    2]
 [   0    0   13  110    7]
 [   1    1   12 1024   68]
 [   1    0    2  196  133]]
평가 점수: 0.7349246231155779


In [19]:
print(10.0 ** np.arange(-2, 3))
grid={'C':10.0 ** np.arange(-2, 3), 'penalty':['l1', 'l2']}
print(grid)

[1.e-02 1.e-01 1.e+00 1.e+01 1.e+02]
{'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]), 'penalty': ['l1', 'l2']}


In [20]:
from sklearn.model_selection import GridSearchCV

clf = GridSearchCV(estimator=log_class, param_grid=grid, cv=5, n_jobs=-1, scoring='f1_macro')
clf.fit(x_train, y_train)

c:\python39\lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
25 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "c:\python39\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\python39\lib\site-packages\sklearn\linear_model\_logistic.py", line 1091, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "c:\python39\lib\site-packages\sklearn\linear_model\_logistic.py", line 61, in _check_solver
    raise ValueError(
ValueError: Solver lbfgs supports only 'l2' or 'none' pen

GridSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [21]:
print(clf.best_estimator_)
print(clf.best_params_)

LogisticRegression(C=0.01)
{'C': 0.01, 'penalty': 'l2'}


In [23]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(C=0.01, penalty='l2')
predict(lr, x_train, y_train, x_test, y_test)

예측값: [4 4 4 ... 4 4 4]
성능 평가 매트릭스: [[   0    0    0    4    0]
 [   0    0    0   20    0]
 [   0    0    0  130    0]
 [   0    0    0 1106    0]
 [   0    0    0  332    0]]
평가 점수: 0.6947236180904522


c:\python39\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [29]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV

n_estimators=[int(x) for x in np.linspace(200, 2000, 5)]
max_features=['auto', 'sqrt', 'log2']
max_depth=[int(x) for x in np.linspace(10, 2000, 5)]

min_samples_leaf=[1, 2, 4, 6]
min_samples_split=[2, 5, 10, 14]

random_grid={
    'n_estimators': n_estimators,
    'max_features': max_features,
    'max_depth': max_depth,
    'min_samples_leaf': min_samples_leaf,
    'min_samples_split': min_samples_split,
    'criterion': ['entropy', 'gini']
}

rf=RandomForestClassifier()
rf_randomcv = RandomizedSearchCV(estimator=rf, param_distributions=random_grid, n_iter=20, cv=3, verbose=2, random_state=100, n_jobs=-1)
predict(rf_randomcv, x_train, y_train, x_test, y_test)

Fitting 3 folds for each of 20 candidates, totalling 60 fits
예측값: [4 4 4 ... 4 4 4]
성능 평가 매트릭스: [[   0    0    1    2    1]
 [   1    0    1   15    3]
 [   0    0   12  112    6]
 [   1    1    9 1022   73]
 [   1    0    2  191  138]]
평가 점수: 0.7361809045226131
